# sesame -- POSIX make. No external build system; zlib is the only dependency.
#
#   make            build sesame
#   make asan       build with ASan/UBSan
#   make test       run the golden tests (requires Rscript for the R oracle)
#   make clean

CC      ?= cc
PREFIX  ?= /usr/local
CFLAGS  ?= -O2 -g
# _GNU_SOURCE makes POSIX/BSD functions (strdup, realpath, getline) visible under
# -std=c11 on glibc, where <string.h> etc. otherwise hide them. Chosen over
# _DEFAULT_SOURCE (unknown to the glibc 2.17 sysroot conda can use) and
# _XOPEN_SOURCE (which would suppress Darwin extensions); _GNU_SOURCE is honored
# by every glibc and is a no-op on macOS, where these are declared by default.
CFLAGS  += -D_GNU_SOURCE -std=c11 -Wall -Wextra -Wpedantic -Wshadow -Wconversion \
           -Wstrict-prototypes -Iinclude
# EXTRA_CFLAGS is appended to every compile (incl. mask.o) and EXTRA_LDFLAGS to
# every link, so `asan` can add sanitizers without clobbering the base flags a
# command-line CFLAGS= override would drop.
CFLAGS  += $(EXTRA_CFLAGS)
LDFLAGS += $(EXTRA_LDFLAGS)

# --- YAME: linked directly for reading .cm masks and for the shared asset
#     store (both AGPL). Built from the pinned submodule so the static lib never
#     goes stale. ---
YAME_DIR := YAME
YAME_LIB := $(YAME_DIR)/libyame.a
HTSLIB   := $(YAME_DIR)/htslib/libhts.a
YAME_INC := -I$(YAME_DIR)/src -I$(YAME_DIR)/htslib

# The whole link line -- libyame.a, libhts.a, and the pthread/z/m/curl set --
# comes from yame-config, generated by YAME's own build. Spelling it by hand is
# how two binaries end up resolving libcurl differently: a bare -lcurl picks
# whatever the linker finds first, which on a conda toolchain is the system one,
# and it then fails against conda's OpenSSL. The $$ defers the command
# substitution to the shell, so it runs after libyame.a (and thus yame-config)
# exists rather than when make parses this file.
YAME_LIBS := $$($(YAME_DIR)/yame-config --libs)

SRC     := src/util.c src/numerics.c src/idat.c src/index.c src/sigdf.c src/prep.c src/qc.c src/dml.c src/cnv.c src/cbs.c src/vcf.c src/region.c src/collapse.c src/liftover.c src/impute.c src/deidentify.c src/mask.c src/cgwrite.c src/attach.c src/cache.c
CLI_SRC := cli/main.c
OBJ     := $(SRC:.c=.o)
CLI_OBJ := $(CLI_SRC:.c=.o)
BIN     := sesame

.PHONY: all asan test test-idat test-betas test-prep test-qmask test-poobah test-noob test-dyebiasL test-pneg test-collapse test-liftover test-impute test-gct test-neighbors test-batch test-qc test-dml test-cg test-attach test-cnv test-cbs test-vcf test-deidentify index cnv-normals registry yame-lib install fuzz fuzz-replay clean

all: $(BIN)

# src/registry.h is a projection of YAME's shared catalog (YAME/tools/registry),
# which is where the asset tags now live -- sesame no longer pins its own. It
# supplies the IDAT bead counts for platform auto-detection and the tag this
# build expects, quoted in the "asset missing" messages. Emission is offline.
registry:
	bash $(YAME_DIR)/tools/make_registry.sh --tool=sesame -o src/registry.h

# Install the binary into $(PREFIX)/bin (honours $(DESTDIR)). Used by the conda
# recipe; `make install PREFIX=/usr/local` for a manual install.
install: $(BIN)
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	cp -f $(BIN) $(DESTDIR)$(PREFIX)/bin/$(BIN)
	chmod 755 $(DESTDIR)$(PREFIX)/bin/$(BIN)

# Incrementally (re)build libyame.a from the checked-out submodule.
yame-lib:
	$(MAKE) -C $(YAME_DIR) lib
$(YAME_LIB) $(HTSLIB): yame-lib

$(BIN): $(OBJ) $(CLI_OBJ) $(YAME_LIB) $(HTSLIB)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJ) $(CLI_OBJ) $(YAME_LIBS)

# main.c stamps in the YAME version it was built against, so `sesame version`
# names the yame that fills the store this binary reads -- and therefore the
# asset tags (InfiniumAnnotation, genomes) that come with it. It also includes
# YAME's yame_ui.h for the help styling, so it takes the same relaxed flags and
# include path as the other YAME-facing units. Needs libyame.a first, since
# yame-config is generated by YAME's build.
cli/main.o: cli/main.c include/sesame.h src/internal.h src/registry.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) \
	    -DSESAME_YAME_VERSION=\"$$($(YAME_DIR)/yame-config --version)\" \
	    -c -o $@ $<

# mask.c includes YAME headers (C99/GNU style); relax pedantic/conversion for it
# only, and give it the YAME include path.
src/mask.o: src/mask.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# cgwrite.c also includes YAME headers; same relaxed rule as mask.o.
src/cgwrite.o: src/cgwrite.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# attach.c also includes YAME headers; same relaxed rule as cgwrite.o.
src/attach.o: src/attach.c include/sesame.h src/internal.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

# cache.c resolves the store root through YAME's shared asset layer (assets.h);
# same relaxed rule as the others.
src/cache.o: src/cache.c include/sesame.h src/internal.h src/registry.h | $(YAME_LIB)
	$(CC) -O2 -g -std=gnu11 -Wall -Iinclude $(YAME_INC) $(EXTRA_CFLAGS) -c -o $@ $<

%.o: %.c include/sesame.h src/internal.h src/registry.h
	$(CC) $(CFLAGS) -c -o $@ $<

asan: clean
	$(MAKE) EXTRA_CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
	        EXTRA_LDFLAGS="-fsanitize=address,undefined"

test: test-idat test-betas test-prep test-qmask test-poobah test-noob test-dyebiasL test-pneg test-collapse test-liftover test-impute test-gct test-neighbors test-batch test-qc test-dml test-cg test-attach test-cnv test-cbs test-vcf test-deidentify

test-idat: $(BIN)
	@tests/run_golden.sh

test-betas: $(BIN) pipeline_dump
	@tests/run_betas.sh

test-prep: $(BIN) pipeline_dump
	@tests/run_prep.sh

test-qmask: $(BIN) pipeline_dump
	@tests/run_qmask.sh

test-poobah: $(BIN) pipeline_dump
	@tests/run_poobah.sh

# The B unit harness links only numerics.o (no other deps).
normexp_test: tests/normexp_test.c src/numerics.o include/sesame.h src/internal.h
	$(CC) $(CFLAGS) -Isrc -o $@ tests/normexp_test.c src/numerics.o -lm

# CBS unit harness: reads a bin-signal vector, prints segments. numerics.o + cbs.o.
cbs_test: tests/cbs_test.c src/cbs.o src/numerics.o include/sesame.h src/internal.h
	$(CC) $(CFLAGS) -Isrc -o $@ tests/cbs_test.c src/cbs.o src/numerics.o -lm

# Validation harness: full-precision library pipeline (links libsesame + YAME),
# so differential tests keep their bit-identical/ULP gates that the .cg product
# (float32) cannot carry.
pipeline_dump: tests/pipeline_dump.c $(OBJ) $(YAME_LIB) $(HTSLIB) include/sesame.h
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ tests/pipeline_dump.c $(OBJ) $(YAME_LIBS)

# M/U TSV -> format-3 .cg, for packing the CNV normal reference (export_cnvnormals.R).
mu2cg: tools/mu2cg.c $(OBJ) $(YAME_LIB) $(HTSLIB) include/sesame.h
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ tools/mu2cg.c $(OBJ) $(YAME_LIBS)

test-noob: $(BIN) normexp_test pipeline_dump
	@tests/run_noob.sh

test-dyebiasL: $(BIN) pipeline_dump
	@tests/run_dyebiasL.sh

test-pneg: $(BIN) pipeline_dump
	@tests/run_pneg.sh

test-collapse: $(BIN) pipeline_dump
	@tests/run_collapse.sh

test-liftover: $(BIN) pipeline_dump
	@tests/run_liftover.sh

test-impute: $(BIN)
	@tests/run_impute.sh

test-gct: $(BIN)
	@tests/run_gct.sh

test-neighbors: $(BIN) pipeline_dump
	@tests/run_neighbors.sh

test-batch: $(BIN)
	@tests/run_batch.sh

test-qc: $(BIN)
	@tests/run_qc.sh

test-dml: $(BIN)
	@tests/run_dml.sh

test-cg: $(BIN) pipeline_dump
	@tests/run_cg.sh

test-attach: $(BIN) mu2cg
	@tests/run_attach.sh

test-cnv: $(BIN)
	@tests/run_cnv.sh

test-cbs: cbs_test
	@tests/run_cbs.sh

test-vcf: $(BIN)
	@tests/run_vcf.sh

test-deidentify: $(BIN)
	@tests/run_deidentify.sh

# Export ordering tables from sesameData (bootstrap; needs Rscript + sesame).
PLATFORMS := HM450 EPIC EPICv2 MSA
index:
	@for p in $(PLATFORMS); do \
	    Rscript tools/export_ordering.R $$p testdata/$$p.ordering.tsv.gz; \
	done

# Export the per-platform CNV normal references (format-3 .cg) from sesameData.
# These are NOT published in the InfiniumAnnotation release, so `yame fetch`
# does not supply them -- this target is how you make one, and `cnv --normals`
# is how you point at it. Genome-level genomeInfo is likewise not here: it lives
# in zhou-lab/genomes (generate with tools/export_genomeinfo.R) and is pulled by
# `yame fetch genomes/<build>`. Needs Rscript.
cnv-normals: mu2cg
	@for p in EPIC EPICv2; do \
	    mkdir -p data/InfiniumAnnotation/$$p; \
	    Rscript tools/export_cnvnormals.R $$p testdata/$$p.ordering.tsv.gz \
	        data/InfiniumAnnotation/$$p/$$p.cnvnormals.mu.tsv.gz && \
	    ./mu2cg data/InfiniumAnnotation/$$p/$$p.cnvnormals.mu.tsv.gz \
	        data/InfiniumAnnotation/$$p/$$p.cnvnormals.cg && \
	    rm -f data/InfiniumAnnotation/$$p/$$p.cnvnormals.mu.tsv.gz; \
	done

# Real fuzzing. Needs a clang with libFuzzer (Linux CI); Apple clang has none.
fuzz:
	$(CC) -std=c11 -g -O1 -Iinclude -fsanitize=fuzzer,address,undefined \
	    fuzz/fuzz_idat.c src/idat.c src/util.c -lz -o fuzz_idat

# Corpus replayer under ASan/UBSan. Works everywhere, incl. Apple clang.
fuzz-replay:
	$(CC) -std=c11 -g -O1 -Iinclude -DSESAME_FUZZ_STANDALONE \
	    -fsanitize=address,undefined \
	    fuzz/fuzz_idat.c src/idat.c src/util.c -lz -o fuzz_replay

clean:
	rm -f $(OBJ) $(CLI_OBJ) $(BIN) normexp_test cbs_test pipeline_dump mu2cg fuzz_idat fuzz_replay
	rm -rf $(BIN).dSYM normexp_test.dSYM fuzz_replay.dSYM fuzz_idat.dSYM
