#!/bin/sh
# Regenerate src/registry.h from the ordering tables in data/.
#
#   tools/make_registry.sh [n] > src/registry.h
#
# Digests are computed from the actual files, so the registry and the artifacts
# cannot drift. Re-run whenever an index is rebuilt, and publish the matching
# file to the tag named in the table.
#
# Tag scheme: <platform>.<artifact>.v<n>, e.g. EPICv2.ordering.v1 -- the asset
# name minus .tsv.gz, plus the version. The tag mirrors the file rather than
# inventing a parallel vocabulary, and it scales to several artifact types per
# platform that version independently:
#
#     EPICv2.ordering.v1  -> EPICv2.ordering.tsv.gz
#     EPICv2.masks.v3     -> EPICv2.masks.tsv.gz     (moves on its own schedule)
#
# Per-platform and per-artifact, so updating one thing is one tag and one row --
# everything else keeps its tag and is not re-downloaded. The asset FILENAME is
# stable across versions: the tag carries the version, and asset names need only
# be unique within a release.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(dirname "$here")
n=${1:-1}
base=${SESAME_BASE_URL:-https://github.com/zwdzwd/sesame-cli/releases/download}

# Bead count (IDAT nSNPsRead) -> platform. Only counts verified end-to-end are
# listed; anything else must be named with --platform rather than guessed at.
beads_for() {
    case $1 in
        HM450)  echo 622399  ;;
        EPIC)   echo 1051815 ;;
        EPICv2) echo 1105209 ;;
        MSA)    echo 384497  ;;
        *)      echo 0       ;;
    esac
}

cat <<EOF
/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Default policy over the (tag, file) retrieval primitive: for each platform,
 * which tag to pull, which file, and the digest it must have.
 *
 * A silently-changed index would silently change betas, so the digest is always
 * verified and a mismatch is fatal, never a warning.
 */
#ifndef SESAME_REGISTRY_H
#define SESAME_REGISTRY_H

#define SESAME_BASE_URL "$base"

typedef struct {
    const char *platform;
    int32_t     beads;     /* IDAT nSNPsRead; 0 = no auto-detect */
    const char *tag;       /* <platform>.<artifact>.v<n> */
    const char *file;      /* stable across versions */
    const char *sha256;
    long long   bytes;
} sesame_reg_t;

static const sesame_reg_t SESAME_REGISTRY[] = {
EOF

for f in "$root"/data/*.ordering.tsv.gz; do
    [ -e "$f" ] || continue
    b=$(basename "$f")
    plat=${b%%.ordering.tsv.gz}
    sum=$(shasum -a 256 "$f" | cut -d' ' -f1)
    size=$(wc -c < "$f" | tr -d ' ')
    printf '    { "%s", %s, "%s.ordering.v%s", "%s",\n      "%s", %s },\n' \
        "$plat" "$(beads_for "$plat")" "$plat" "$n" "$b" "$sum" "$size"
done

cat <<'EOF'
    { NULL, 0, NULL, NULL, NULL, 0 }
};

#endif /* SESAME_REGISTRY_H */
EOF
