#!/bin/sh
# Regenerate src/registry.h by pinning each platform's SHA256SUMS digest from the
# published InfiniumAnnotation repo at a tag.
#
#   tools/make_registry.sh v1 > src/registry.h
#
# Repo layout: <base>/<tag>/<platform>/{SHA256SUMS, <platform>.ordering.tsv.gz,
# <platform>.hg38.mask.cm, ...}. We pin sha256(<platform>/SHA256SUMS) as the hard
# trust anchor; every file digest chains from there. A platform not yet published
# at the tag gets a NULL anchor and cannot be fetched (but its bead count still
# drives auto-detection).
set -eu

tag=${1:-v1}
base=${SESAME_BASE_URL:-https://github.com/zhou-lab/InfiniumAnnotation/raw}

# platform | bead count (IDAT nSNPsRead) | ordering filename
set -- \
  "EPIC   1051815 EPIC.ordering.tsv.gz" \
  "EPICv2 1105209 EPICv2.ordering.tsv.gz" \
  "HM450  622399  HM450.ordering.tsv.gz" \
  "MSA    384497  MSA.ordering.tsv.gz"

cat <<EOF
/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Per platform: the IDAT bead count (for auto-detection), the ordering file
 * name, and the sha256 of <platform>/SHA256SUMS at the pinned tag -- the hard
 * trust anchor. NULL anchor = not published at this tag yet.
 */
#ifndef SESAME_REGISTRY_H
#define SESAME_REGISTRY_H

#define SESAME_BASE_URL     "$base"
#define SESAME_DEFAULT_TAG  "$tag"
#define SESAME_SUMS_FILE    "SHA256SUMS"

typedef struct {
    const char *platform;
    int32_t     beads;        /* IDAT nSNPsRead; 0 = no auto-detect */
    const char *ordering;     /* ordering table filename */
    const char *sums_sha256;  /* sha256 of <platform>/SHA256SUMS; NULL = unpublished */
} sesame_reg_t;

static const sesame_reg_t SESAME_REGISTRY[] = {
EOF

for row in "$@"; do
    set -- $row
    plat=$1; beads=$2; ord=$3
    url="$base/$tag/$plat/SHA256SUMS"
    sha=$(curl -sfL "$url" 2>/dev/null | shasum -a 256 | cut -d' ' -f1 || true)
    # curl of a 404 yields empty -> NULL anchor
    if curl -sfIL "$url" >/dev/null 2>&1 && [ -n "$sha" ]; then
        printf '    { "%s", %s, "%s", "%s" },\n' "$plat" "$beads" "$ord" "$sha"
    else
        printf '    { "%s", %s, "%s", NULL },  /* not published at %s */\n' \
            "$plat" "$beads" "$ord" "$tag"
    fi
done

cat <<'EOF'
    { NULL, 0, NULL, NULL }
};

/* --- Genome-level annotation (seqinfo/gaps/cytoband), hosted separately in
 * zhou-lab/genomes so plotting tools can reuse it. Raw git paths, one repo-wide
 * tag. Layout: <base>/<tag>/<genome>/{SHA256SUMS, seqinfo.tsv.gz, gaps.tsv.gz,
 * cytoband.tsv.gz}. Trust anchor = sha256(<genome>/SHA256SUMS) at the tag. */
EOF

gbase=${SESAME_GENOME_BASE_URL:-https://github.com/zhou-lab/genomes/raw}
gtag=${SESAME_GENOME_TAG:-v1}

cat <<EOF
#define SESAME_GENOME_BASE_URL  "$gbase"
#define SESAME_GENOME_TAG       "$gtag"

typedef struct {
    const char *genome;
    const char *sums_sha256;  /* sha256 of <genome>/SHA256SUMS; NULL = unpublished */
} sesame_genome_reg_t;

static const sesame_genome_reg_t SESAME_GENOME_REGISTRY[] = {
EOF

for genome in hg38; do
    url="$gbase/$gtag/$genome/SHA256SUMS"
    sha=$(curl -sfL "$url" 2>/dev/null | shasum -a 256 | cut -d' ' -f1 || true)
    if curl -sfIL "$url" >/dev/null 2>&1 && [ -n "$sha" ]; then
        printf '    { "%s", "%s" },\n' "$genome" "$sha"
    else
        printf '    { "%s", NULL },  /* not published at %s */\n' "$genome" "$gtag"
    fi
done

cat <<'EOF'
    { NULL, NULL }
};

#endif /* SESAME_REGISTRY_H */
EOF
