/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * The pinned annotation tag, and the digest of that tag's SHA256SUMS -- the
 * trust anchor. Per-file digests come from SHA256SUMS itself, so verification
 * and de-duplication work for any tag, while the default tag stays anchored to
 * something compiled in.
 */
#ifndef SESAME_REGISTRY_H
#define SESAME_REGISTRY_H

#define SESAME_BASE_URL     "https://github.com/zhou-lab/InfiniumAnnotation/raw"
#define SESAME_DEFAULT_TAG  "v1"
#define SESAME_SUMS_FILE    "SHA256SUMS"
#define SESAME_SUMS_SHA256  "be729f1b570b1a3620c3bb4d328c667339e952697f534a4378df7822d756614f"

typedef struct {
    const char *platform;
    int32_t     beads;     /* IDAT nSNPsRead; 0 = no auto-detect */
    const char *file;
} sesame_reg_t;

static const sesame_reg_t SESAME_REGISTRY[] = {
    { "EPIC", 1051815, "EPIC.ordering.tsv.gz" },
    { "EPICv2", 1105209, "EPICv2.ordering.tsv.gz" },
    { "HM450", 622399, "HM450.ordering.tsv.gz" },
    { "MSA", 384497, "MSA.ordering.tsv.gz" },
    { NULL, 0, NULL }
};

#endif /* SESAME_REGISTRY_H */
